; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{YOUR-GUID-HERE}}
AppName=Photo Transfer App
AppVersion=1.0
DefaultDirName={pf}\PhotoTransferApp
DefaultGroupName=Photo Transfer App
OutputDir=.
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "dist\photos\photos.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "icons\folder.png"; DestDir: "{app}\icons"; Flags: ignoreversion
Source: "app_settings.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "start_photos.bat"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\Photo Transfer App"; Filename: "{app}\start_photos.bat"
Name: "{group}\{cm:UninstallProgram,Photo Transfer App}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\start_photos.bat"; Description: "{cm:LaunchProgram,Photo Transfer App}"; Flags: nowait postinstall skipifsilent